name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - 'nuget.config'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release